/* BMO core: export —— 生成可导入浏览器的书签 HTML（Netscape 格式）与进度 JSON */
window.BMO = window.BMO || {};

BMO.Export = (function () {
  const esc = s => String(s == null ? '' : s).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

  /**
   * @param {object} state
   * @param {object} opts {rootName?: string|null, includeTrash?: boolean}
   *   rootName 为 null 时顶层分类直接铺在根 DL 下（Chrome 导入会统一放进「已导入」）；
   *   给定名字时会包一层文件夹，便于在浏览器里一眼认出。
   */
  function html(state, opts) {
    const o = opts || {};
    const Mo = BMO.Model;
    const now = Math.floor(Date.now() / 1000);
    const items = state.items.filter(i => o.includeTrash ? true : !i.trashed);
    const L = [];
    L.push('<!DOCTYPE NETSCAPE-Bookmark-file-1>');
    L.push('<!-- Generated by Marknest -->');
    L.push('<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">');
    L.push('<TITLE>Bookmarks</TITLE>');
    L.push('<H1>Bookmarks</H1>');
    L.push('<DL><p>');

    const link = (i, pad) => L.push(`${pad}<DT><A HREF="${esc(i.url)}" ADD_DATE="${i.added || now}">${esc(i.name)}</A>`);
    const emit = (fid, depth) => {
      const pad = '    '.repeat(depth);
      items.filter(i => i.folder === fid).forEach(i => link(i, pad));
      for (const sub of Mo.subFolders(state, fid)) {
        L.push(`${pad}<DT><H3 ADD_DATE="${now}">${esc(sub.name)}</H3>`);
        L.push(`${pad}<DL><p>`);
        emit(sub.id, depth + 1);
        L.push(`${pad}</DL><p>`);
      }
    };

    let body = [];
    (function () {
      const tmp = L.length;
      for (const f of Mo.topFolders(state)) {
        L.push(`    <DT><H3 ADD_DATE="${now}">${esc(f.name)}</H3>`);
        L.push('    <DL><p>');
        emit(f.id, 2);
        L.push('    </DL><p>');
      }
      const orphans = items.filter(i => !Mo.folderById(state, i.folder));
      if (orphans.length) {
        L.push(`    <DT><H3 ADD_DATE="${now}">${esc(BMO.i18n.t('uncategorized'))}</H3>`);
        L.push('    <DL><p>');
        orphans.forEach(i => link(i, '        '));
        L.push('    </DL><p>');
      }
      body = L.splice(tmp);
    })();

    if (o.rootName) {
      L.push(`    <DT><H3 ADD_DATE="${now}" PERSONAL_TOOLBAR_FOLDER="true">${esc(o.rootName)}</H3>`);
      L.push('    <DL><p>');
      L.push(...body.map(s => '    ' + s));
      L.push('    </DL><p>');
    } else {
      L.push(...body);
    }
    L.push('</DL><p>');
    return { text: L.join('\n') + '\n', links: items.length, folders: state.folders.length };
  }

  function json(state, opts) {
    const slim = !(opts && opts.full);
    const o = {
      app: 'marknest', version: 1, savedAt: new Date().toISOString(),
      source: state.source, capabilities: state.capabilities || null,
      ui: state.ui || {}, rules: state.rules || [],
      folders: state.folders,
      items: state.items.map(i => slim
        ? { id: i.id, name: i.name, url: i.url, folder: i.folder, home: i.home, orig: i.orig, added: i.added, used: i.used, visits: i.visits, tags: i.tags, check: i.check, moved: i.moved, trashed: i.trashed, srcId: i.srcId || null }
        : i),
    };
    return JSON.stringify(o);
  }

  /** 从进度 JSON 恢复 */
  function fromJson(text) {
    const o = JSON.parse(text);
    if (!o || !Array.isArray(o.folders) || !Array.isArray(o.items)) throw new Error('bad progress file');
    return o;
  }

  return { html, json, fromJson, esc };
})();
